#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BluetoothProximitySensor.Resource", IsApplication=true)]

namespace BluetoothProximitySensor
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_big = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int button_bluetooth_choose_device = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int button_scan = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int button_start = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int button_stop = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int devices = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int imageView = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int paired_devices = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int title_devices = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int title_paired_devices = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BluetoothDeviceChoose = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DevicesListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040011
			public const int button_choose_device = 2130968593;
			
			// aapt resource value: 0x7f040001
			public const int button_scan = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int button_start = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int button_stop = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int connection_lost = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int device_choose_confirm = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int device_found = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int motion_detected = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int no = 2130968592;
			
			// aapt resource value: 0x7f040005
			public const int none_found = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int successfully_paired = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int title_devices = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int title_main = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int title_no_paired_devices = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int title_paired_devices = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int unable_to_connect = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int yes = 2130968591;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
